create table checkin (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id BIGINT references users(id),
  year INT NOT NULL,
  month INT NOT NULL,
  day INT NOT NULL,
  acc INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
